# Generated by Django 5.2.4 on 2025-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumnos_profesores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
    ]
